#!/bin/sh -e
#
# /etc/init.d/mjpg_streamer: Start the motion detection
#
### BEGIN INIT INFO
# Provides:	  motion
# Required-Start: $local_fs $syslog $remote_fs
# Required-Stop: $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start mjpg_streamer
### END INIT INFO


NAME=mjpg_streamer
PATH_BIN=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/bin/mjpg_streamer
PIDFILE=/var/run/$NAME.pid
OPTIONS="-b -i /usr/lib/input_uvc.so -d /dev/video0 -r 1280x720 -f 20 -n -y -o /usr/lib/output_http.so -p 8090 -w /var/www/mjpg_streamer"
DESC="daemon"

RET=0

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME" 
	if start-stop-daemon --start --exec $DAEMON $OPTIONS ; then
            log_end_msg 0
        else
            log_end_msg 1
            RET=1
        fi
    ;;

  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    kill -9 `pgrep $NAME`
    ;;

  restart)
    stop
    sleep 5;
    start    
    ;;

  status)
    pid=`pidof $NAME`
    if [ -z "$pid" ]; then
	echo "$NAME running"
    else
	echo "$NAME not running"
    fi
    RET=0  
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    RET=1
    ;;
esac


exit $RET
